title: multiobjective-optimizations
author: Sparsh A.
execute:
  execute_notebooks: "off"
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
repository:
  url: https://github.com/RecoHut-Projects/multiobjective-optimizations
  path_to_book: docs
  branch: main
launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true
